# .github/workflows/ci.yml
name: Test, Build & Publish

on:
  push:
    branches:
      - main

jobs:
  test-build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Determine version bump
        id: version
        run: |
          COMMITS=$(git log $(git describe --tags --abbrev=0)..HEAD --oneline)
          if echo "$COMMITS" | grep -q "^feat:"; then
            echo "bump=minor" >> $GITHUB_OUTPUT
          elif echo "$COMMITS" | grep -q "^fix:\|^refactor:"; then
            echo "bump=patch" >> $GITHUB_OUTPUT
          else
            echo "bump=none" >> $GITHUB_OUTPUT
          fi

      - name: Bump version
        if: steps.version.outputs.bump != 'none'
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          npm version ${{ steps.version.outputs.bump }} -m "Release %s"

      - name: Build
        run: npm run build

      - name: Publish to NPM
        if: steps.version.outputs.bump != 'none'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push tags
        if: steps.version.outputs.bump != 'none'
        run: git push --follow-tags
